
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    auth: {
        domain: 'dev-bz3b8mki.us.auth0.com',
        clientId: 'wJQikMK7YuJtteLkWWgTbWjdzWZdhdU3',
        redirectUri: window.location.origin
    }
  };
